apiVersion: apps/v1
kind: Deployment
metadata:
  name: assistant
  labels:
    app: assistant
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: assistant
  template:
    metadata:
      labels:
        app: assistant
    spec:
      containers:
      - name: assistant
        image: apipa169/assistant-relay:3.2.0.1
        imagePullPolicy: IfNotPresent
        command: ["/init/init.sh"]
        volumeMounts:
        - name: config
          mountPath: /config/
        - name: init
          mountPath: /init/
        ports:
        - containerPort: 3000
      volumes:
      - name: config
        secret:
          secretName: config
      - name: init
        configMap:
          name: init
          defaultMode: 0700
---
apiVersion: v1
kind: Service
metadata:
  name: assistant
spec:
  ports:
  - port: 3000
    targetPort: 3000
    name: http
    protocol: TCP
  type: LoadBalancer
  selector:
    app: assistant
